name: Publish API Spec

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Create settings.xml
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.MASTER_TOKEN }}</password>
            </server>
          </servers>
        </settings>" > ~/.m2/settings.xml

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -DskipTests

    - name: Clean up
      run: rm -f ~/.m2/settings.xml
